# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{secrets.TOKEN}} 
      with: 
         tag_name: v${{github.run_number}}
         release_name: Release V${{github.run_number}} 

    - name: Update version
      run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -DskipTests --file pom.xml
      env:
         GITHUB_TOKEN: ${{secrets.TOKEN}} 


 
